#ifndef FR_VARIABLES_H
#define FR_VARIABLES_H

#include "Variables_Structure.h"

#define HANDLING_POINT_12_PATH1 0
#define HANDLING_POINT_23_PATH1 1
#define HANDLING_POINT_12_PATH2 2
#define HANDLING_POINT_23_PATH2 3
#define FIXATION_POINT_2_X 4
#define FOAMXWIDTH 5
#define FOAM_HEIGHT 6
#define FEEDER_EXTRACTION_SPEED 7

#define FORK_SENSOR_PAGE 8

#define IR_CNC_INLET_SENSOR 9
#define IR_CNC_EXIT_SENSOR 10

#define FORK2_NAIL1_LM_SENSOR 11
#define FORK2_NAIL2_LM_SENSOR 12
#define FORK2_NAIL3_LM_SENSOR 13

#define FORK3_NAIL1_LM_SENSOR 14
#define FORK3_NAIL2_LM_SENSOR 15
#define FORK3_NAIL3_LM_SENSOR 16

#define CNC_GATE_FIXATION1_LM_SENSOR 17
#define CNC_GATE_FIXATION2_LM_SENSOR 18
#define CNC_GATE_FIXATION3_LM_SENSOR 19

#define FORK1_FRAME_X_SENSOR 20
#define FORK1_FORK2_X_SENSOR 21
#define FORK2_FORK3_X_SENSOR 22
#define FORK3_FRAME_X_SENSOR 23

#define FORK1_Z_UP_SENSOR 24
#define FORK1_Z_DOWN_SENSOR 25

#define FORK2_Z_UP_SENSOR 26
#define FORK2_Z_DOWN_SENSOR 27

#define FORK3_Z_UP_SENSOR 28
#define FORK3_Z_DOWN_SENSOR 29

#define CNC_GATE_Z_UP_SENSOR 30
#define CNC_GATE_Z_DOWN_SENSOR 31

extern Variable FR_Vars[];
extern const int NUM_FR_VARS;

#endif